# Generated by Django 5.2.10 on 2026-02-02 14:05

import django.utils.timezone
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "user_code",
                    models.CharField(
                        default=core.utils.generate_id,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_email", models.CharField(max_length=64, unique=True)),
                ("user_name", models.CharField(blank=True, default="", max_length=32)),
                ("user_created", models.DateField(default=django.utils.timezone.now)),
                ("user_last_activity", models.DateField(default=django.utils.timezone.now)),
                ("user_own_collections", models.JSONField(blank=True, default=list)),
                ("user_shared_collections", models.JSONField(blank=True, default=list)),
                ("user_things", models.JSONField(blank=True, default=list)),
                ("user_headline", models.CharField(blank=True, default="", max_length=64)),
                ("user_thumbnail", models.CharField(blank=True, default="", max_length=16)),
                ("user_hero", models.CharField(blank=True, default="", max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "collection_code",
                    models.CharField(
                        default=core.utils.generate_id,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collection_owner", models.CharField(max_length=6)),
                ("collection_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("collection_headline", models.CharField(max_length=64)),
                (
                    "collection_description",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("collection_thumbnail", models.CharField(blank=True, default="", max_length=16)),
                ("collection_hero", models.CharField(blank=True, default="", max_length=16)),
                (
                    "collection_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=8,
                    ),
                ),
                ("collection_articles", models.JSONField(blank=True, default=list)),
                ("collection_invites", models.JSONField(blank=True, default=list)),
                ("collection_theeeme", models.CharField(default="BAR_CEL_ONA", max_length=32)),
            ],
            options={
                "db_table": "collections",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "faq_code",
                    models.CharField(
                        default=core.utils.generate_id,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("faq_thing", models.CharField(max_length=6)),
                ("faq_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("faq_questioner", models.CharField(max_length=6)),
                ("faq_question", models.CharField(max_length=64)),
                ("faq_answer", models.CharField(blank=True, default="", max_length=256)),
                ("faq_is_visible", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "faqs",
            },
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "rsvp_code",
                    models.CharField(
                        default=core.utils.generate_id,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rsvp_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("user_code", models.CharField(max_length=6)),
                ("user_email", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "rsvps",
            },
        ),
        migrations.CreateModel(
            name="Thing",
            fields=[
                (
                    "thing_code",
                    models.CharField(
                        default=core.utils.generate_id,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "thing_type",
                    models.CharField(
                        choices=[
                            ("GIFT_ARTICLE", "Gift Article"),
                            ("SELL_ARTICLE", "Sell Article"),
                            ("ORDER_ARTICLE", "Order Article"),
                        ],
                        default="GIFT_ARTICLE",
                        max_length=16,
                    ),
                ),
                ("thing_owner", models.CharField(max_length=6)),
                ("thing_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("thing_headline", models.CharField(max_length=64)),
                ("thing_description", models.CharField(blank=True, default="", max_length=256)),
                ("thing_thumbnail", models.CharField(blank=True, default="", max_length=16)),
                ("thing_pictures", models.JSONField(blank=True, default=list)),
                (
                    "thing_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("TAKEN", "Taken"),
                        ],
                        default="ACTIVE",
                        max_length=8,
                    ),
                ),
                ("thing_faq", models.JSONField(blank=True, default=list)),
                (
                    "thing_fee",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("thing_deal", models.JSONField(blank=True, default=list)),
                ("thing_available", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "things",
            },
        ),
    ]
