# Generated by Django 5.2.10 on 2026-02-03 09:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_collection_theeeme"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="collection",
            name="collection_theeeme",
            field=models.ForeignKey(
                db_column="collection_theeeme",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.theeeme",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_created",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_last_activity",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
