# Generated by Django 5.2.10 on 2026-02-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_password_alter_collection_collection_theeeme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='collection_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
