# Generated by Django 5.2.10 on 2026-02-05 08:16

import core.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_collection_code_to_rsvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('reservation_code', models.CharField(default=core.utils.generate_id, max_length=6, primary_key=True, serialize=False)),
                ('reservation_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('thing_code', models.CharField(max_length=6)),
                ('requester_code', models.CharField(max_length=6)),
                ('requester_email', models.CharField(max_length=64)),
                ('owner_code', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
            ],
            options={
                'db_table': 'reservation_requests',
            },
        ),
    ]
