# Generated by Django 5.2.10 on 2026-02-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_reservation_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='thing_type',
            field=models.CharField(choices=[('GIFT_ARTICLE', 'Gift Article'), ('SELL_ARTICLE', 'Sell Article'), ('ORDER_ARTICLE', 'Order Article'), ('RENT_ARTICLE', 'Rent Article'), ('LEND_ARTICLE', 'Lend Article'), ('SHARE_ARTICLE', 'Share Article')], default='GIFT_ARTICLE', max_length=16),
        ),
    ]
