# Generated by Django 5.2.10 on 2026-02-05 19:24

import core.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_thing_thing_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingPeriod",
            fields=[
                (
                    "booking_code",
                    models.CharField(
                        default=core.utils.generate_id,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("thing_code", models.CharField(db_index=True, max_length=6)),
                ("requester_code", models.CharField(max_length=6)),
                ("requester_email", models.CharField(max_length=64)),
                ("owner_code", models.CharField(max_length=6)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "db_table": "booking_periods",
            },
        ),
    ]
