# Generated by Django 5.2.10 on 2026-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_change_theeeme_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="rsvp",
            name="rsvp_action",
            field=models.CharField(
                choices=[
                    ("MAGIC_LINK", "Magic Link"),
                    ("COLLECTION_INVITE", "Collection Invite"),
                    ("RESERVATION_ACCEPT", "Reservation Accept"),
                    ("RESERVATION_REJECT", "Reservation Reject"),
                    ("BOOKING_ACCEPT", "Booking Accept"),
                    ("BOOKING_REJECT", "Booking Reject"),
                ],
                default="MAGIC_LINK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rsvp",
            name="rsvp_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="rsvp",
            name="rsvp_target_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
