# Generated by Django 5.2.10 on 2026-02-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_rsvp_action_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingperiod",
            name="thing_type",
            field=models.CharField(default="GIFT_THING", max_length=12),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookingperiod",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="rsvp_action",
            field=models.CharField(
                choices=[
                    ("MAGIC_LINK", "Magic Link"),
                    ("COLLECTION_INVITE", "Collection Invite"),
                    ("BOOKING_ACCEPT", "Booking Accept"),
                    ("BOOKING_REJECT", "Booking Reject"),
                ],
                default="MAGIC_LINK",
                max_length=20,
            ),
        ),
    ]
