# Generated by Django 5.2.10 on 2026-02-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_unify_booking_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReservationRequest",
        ),
        migrations.AddField(
            model_name="bookingperiod",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingperiod",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
